plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1' // for shading, needed for plugins
    id 'net.runelite' version 'latest.release' // this gives you the runelite{} block
}

group 'com.ryuky.client.plugins.skillloottracker'
version '1.5.0'

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = 'https://repo.runelite.net'
    }
}

def runeliteVersion = 'latest.release'

// This is the block you need for the icon
runelite {
    iconPath = "icon.png"  // file must be in src/main/resources/icon.png
}

dependencies {
    compileOnly group: 'net.runelite', name: 'api', version: runeliteVersion
    compileOnly group: 'net.runelite', name: 'client', version: runeliteVersion

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    // GSON
    compileOnly 'com.google.code.gson:gson:2.10.1'

    // Testing
    testImplementation group: 'net.runelite', name: 'api', version: runeliteVersion
    testImplementation group: 'net.runelite', name: 'client', version: runeliteVersion
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    options.release = 11
}