plugins {
    id 'java'
}

group 'com.ryuky.client.plugins.skillloottracker'
version '1.0.0'

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = 'https://repo.runelite.net'
    }
}

def runeliteVersion = 'latest.release'

dependencies {
    compileOnly group: 'net.runelite', name: 'api', version: runeliteVersion
    compileOnly group: 'net.runelite', name: 'client', version: runeliteVersion

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    // GSON
    compileOnly 'com.google.code.gson:gson:2.10.1'

    // Testing
    testImplementation group: 'net.runelite', name: 'api', version: runeliteVersion
    testImplementation group: 'net.runelite', name: 'client', version: runeliteVersion
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    options.release = 11
}