displayName=Skilling Loot Tracker
author=RyUkY
description=Resource tracking and profit from gathering skills Stop guessing your GP/hr. Know exactly what your grind is worth.
tags=Skilling, Loot, Tracker, Fishing, Mining, Woodcutting, Farming, Hunter
version=2.5.0
plugins=com.ryuky.client.plugins.skillloottracker.SkillLootTrackerPlugin
build=standard